// lib/seo/graphData.ts
//
// Reads the link graph out of Supabase and normalises it into the plain shapes
// lib/seo/linkGraph.ts scores. Everything is wrapped in React's `cache` so a
// single page render does one read of each table no matter how many blocks ask
// for recommendations.
//
// New columns (cluster, revenue_priority, entity_aliases, intent_stage,
// page_type, primary_entry_slug) are read defensively with `??`. Every query
// here uses `select("*")`, so the code runs correctly against a database where
// scripts/sql/003_seo_graph.sql has not been applied yet — those pages
// simply fall back to inferred clusters and default priorities.

import { cache } from "react";
import { getSupabaseServerSafe } from "@/lib/supabase/safe";
import {
  clusterSetFor,
  defaultsForCategory,
  resolveCluster,
  type ClusterSet,
  type IntentStage,
  type PageType,
} from "./clusters";
import type { GraphEntry, GraphPost } from "./linkGraph";

export type Site = "main" | "crypto";

type TableSet = { entries: string; posts: string };

export function tablesFor(site: Site): TableSet {
  return site === "crypto"
    ? { entries: "crypto_entries", posts: "crypto_blog_posts" }
    : { entries: "entries", posts: "blog_posts" };
}

/** Strips markup and collapses whitespace so entity matching sees prose. */
export function toPlainText(html: string): string {
  return html
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/\s+/g, " ")
    .toLowerCase()
    .trim();
}

// ── Inbound link census ──────────────────────────────────────────────

/**
 * Counts contextual internal links pointing at each directory listing.
 *
 * Two sources count as a real inbound link: a slug pinned on a post, and an
 * <a href> in the article body that resolves to the listing. Recommendation
 * blocks are deliberately *not* counted — they're generated by this very
 * engine, so counting them would make the authority-need component chase its
 * own tail and permanently starve genuinely orphaned pages.
 */
export const getInboundLinkCounts = cache(
  async (site: Site): Promise<Map<string, number>> => {
    const counts = new Map<string, number>();
    const sb = getSupabaseServerSafe();
    if (!sb) return counts;

    const { posts } = tablesFor(site);
    const { data, error } = await sb
      .from(posts)
      .select("slug, content, related_entry_slugs")
      .eq("status", "published");

    if (error || !data) {
      if (error) console.error("[getInboundLinkCounts]", error.message);
      return counts;
    }

    const bump = (slug: string) => counts.set(slug, (counts.get(slug) ?? 0) + 1);

    for (const row of data as { content: string | null; related_entry_slugs: string[] | null }[]) {
      const seenInThisPost = new Set<string>();

      for (const slug of row.related_entry_slugs ?? []) {
        if (slug && !seenInThisPost.has(slug)) {
          seenInThisPost.add(slug);
          bump(slug);
        }
      }

      // href="/earn-money/freecash-review" → "freecash-review".
      // Same post linking the same listing five times is still one vote.
      const hrefs = (row.content ?? "").matchAll(/href=["']\/(?:[a-z0-9-]+)\/([a-z0-9-]+)["']/gi);
      for (const m of hrefs) {
        const slug = m[1];
        if (slug && !seenInThisPost.has(slug)) {
          seenInThisPost.add(slug);
          bump(slug);
        }
      }
    }

    return counts;
  }
);

// ── Entries ──────────────────────────────────────────────────────────

type RawEntry = {
  id: string;
  slug: string;
  title: string;
  category: string;
  short_description: string | null;
  tags: string[] | null;
  referral_url: string | null;
  updated_at: string;
  cluster?: string | null;
  revenue_priority?: number | null;
  entity_aliases?: string[] | null;
  chain?: string | null;
};

function normaliseEntry(
  row: RawEntry,
  set: ClusterSet,
  inbound: Map<string, number>
): GraphEntry {
  const cluster = resolveCluster(
    row.cluster,
    { slug: row.slug, category: row.category, tags: row.tags ?? [], title: row.title },
    set
  );

  const explicitPriority = row.revenue_priority;
  const revenuePriority =
    typeof explicitPriority === "number" && explicitPriority > 0
      ? explicitPriority
      : (set.byId.get(cluster)?.defaultRevenuePriority ?? 50);

  return {
    id: row.id,
    slug: row.slug,
    title: row.title,
    category: row.category,
    cluster,
    tags: row.tags ?? [],
    aliases: row.entity_aliases ?? [],
    shortDescription: row.short_description ?? "",
    revenuePriority,
    hasReferral: Boolean(row.referral_url),
    updatedAt: row.updated_at,
    inboundLinks: inbound.get(row.slug) ?? 0,
    chain: row.chain ?? undefined,
  };
}

/**
 * The full candidate pool.
 *
 * Read whole rather than pre-filtered: at 151 and 47 rows the table is far
 * smaller than the cost of getting the ranking wrong, and the old 300-row
 * `order by rating` cap silently made low-rated listings — exactly the
 * under-linked ones authority balancing exists to help — invisible to the
 * scorer the moment the directory outgrew it.
 */
const getRawEntryRows = cache(async (site: Site): Promise<RawEntry[]> => {
  const sb = getSupabaseServerSafe();
  if (!sb) return [];

  const { entries } = tablesFor(site);
  const { data, error } = await sb.from(entries).select("*");

  if (error || !data) {
    if (error) console.error("[getRawEntryRows]", error.message);
    return [];
  }
  return data as RawEntry[];
});

export const getEntryPool = cache(async (site: Site): Promise<GraphEntry[]> => {
  const [rows, inbound] = await Promise.all([
    getRawEntryRows(site),
    getInboundLinkCounts(site),
  ]);
  const set = clusterSetFor(site);
  return rows.map((row) => normaliseEntry(row, set, inbound));
});

/**
 * The full rows, keyed by id, so a caller can turn the engine's picks back into
 * whatever shape it renders. Shares getRawEntryRows' cache entry with
 * getEntryPool, so scoring and rendering cost one query between them.
 */
export const getEntryRowsById = cache(
  async (site: Site): Promise<Map<string, Record<string, unknown>>> => {
    const rows = await getRawEntryRows(site);
    return new Map(rows.map((r) => [r.id, r as unknown as Record<string, unknown>]));
  }
);

export const getEntryPoolBySlug = cache(
  async (site: Site): Promise<Map<string, GraphEntry>> => {
    const pool = await getEntryPool(site);
    return new Map(pool.map((e) => [e.slug, e]));
  }
);

// ── Posts ────────────────────────────────────────────────────────────

type RawPost = {
  id: string;
  slug: string;
  title: string;
  category: string;
  content: string | null;
  tags: string[] | null;
  target_keyword: string | null;
  secondary_keywords: string[] | null;
  published_at: string | null;
  updated_at: string;
  cluster?: string | null;
  intent_stage?: string | null;
  page_type?: string | null;
  primary_entry_slug?: string | null;
  chain?: string | null;
};

const VALID_STAGES = new Set<string>(["DISCOVER", "LEARN", "COMPARE", "DECIDE", "ACT"]);

export function normalisePost(row: RawPost, set: ClusterSet): GraphPost {
  const fallback = defaultsForCategory(row.category);

  const cluster = resolveCluster(
    row.cluster,
    {
      slug: row.slug,
      category: row.category,
      tags: row.tags ?? [],
      title: row.title,
      keywords: [row.target_keyword ?? "", ...(row.secondary_keywords ?? [])],
    },
    set
  );

  const stage =
    row.intent_stage && VALID_STAGES.has(row.intent_stage)
      ? (row.intent_stage as IntentStage)
      : fallback.stage;

  return {
    id: row.id,
    slug: row.slug,
    title: row.title,
    category: row.category,
    cluster,
    tags: row.tags ?? [],
    targetKeyword: row.target_keyword ?? "",
    secondaryKeywords: row.secondary_keywords ?? [],
    intentStage: stage,
    pageType: (row.page_type as PageType) || fallback.pageType,
    text: toPlainText(row.content ?? ""),
    primaryEntrySlug: row.primary_entry_slug ?? undefined,
    publishedAt: row.published_at ?? undefined,
    updatedAt: row.updated_at,
    chain: row.chain ?? undefined,
  };
}

export const getPostPool = cache(async (site: Site): Promise<GraphPost[]> => {
  const sb = getSupabaseServerSafe();
  if (!sb) return [];

  const { posts } = tablesFor(site);
  const { data, error } = await sb.from(posts).select("*").eq("status", "published");

  if (error || !data) {
    if (error) console.error("[getPostPool]", error.message);
    return [];
  }

  const set = clusterSetFor(site);
  return (data as RawPost[]).map((row) => normalisePost(row, set));
});

/**
 * Turns the app-level BlogPost already loaded by a page into a GraphPost,
 * avoiding a second fetch of the article we're literally rendering.
 */
export function postToGraphPost(
  post: {
    id: string;
    slug: string;
    title: string;
    category: string;
    content: string;
    tags: string[];
    targetKeyword: string;
    secondaryKeywords: string[];
    publishedAt?: string;
    updatedAt: string;
    cluster?: string;
    intentStage?: string;
    pageType?: string;
    primaryEntrySlug?: string;
    chain?: string;
  },
  site: Site
): GraphPost {
  return normalisePost(
    {
      id: post.id,
      slug: post.slug,
      title: post.title,
      category: post.category,
      content: post.content,
      tags: post.tags,
      target_keyword: post.targetKeyword,
      secondary_keywords: post.secondaryKeywords,
      published_at: post.publishedAt ?? null,
      updated_at: post.updatedAt,
      cluster: post.cluster ?? null,
      intent_stage: post.intentStage ?? null,
      page_type: post.pageType ?? null,
      primary_entry_slug: post.primaryEntrySlug ?? null,
      chain: post.chain ?? null,
    },
    clusterSetFor(site)
  );
}
